#!/usr/bin/env python
"""
DESCRIPTION:
+ Takes in data from cameras and distributes it to the external package nodes that process it.
+ Recieves the processed data from the external nodes and publishes it to the nodes implementing the moving of Baxter.


SUBSCRIBERS:
+ leftCamera (/cameras/left_hand_camera/image) - Wrist left camera's image
  type = sensor_msgs/Image

+ calibrationMatrixLeftSub (/cameras/left_hand_camera/camera_info) - Camera's calibration matrix
  type = sensor_msg/CameraInfo

+ rightCamera (/cameras/right_hand_camera/image) - Wrist right camera's image
  type = sensor_msgs/Image

+ calibrationMatrixRightSub (/cameras/right_hand_camera/camera_info) - Camera's calibration matrix
  type = sensor_msg/CameraInfo

+ rectifiedDistributor (/image_rect) - Redistributes the rectified image to the april tags detector
  type = sensor_msgs/Image

+ apriltags (/tag_detections) - Subscribes to the april tag classification data stream
  type = apriltag_ros/AprilTagDetectionArray


PUBLISHERS:
+ calibrationMatrixLeftPub (/camera_rect/camera_info) - camera's calibration matrix
type = sensor_msgs/CameraInfo

+ redistributeCameraInfo (/camera_info) - actual image from Baxter's right wrist camera
type = sensor_msgs/Image

+ redistributeCameraInfo2 (/camera_rect/camera_info) - actual image from Baxter's right wrist camera
type = sensor_msgs/Image

+ pub (/image_raw) - raw camera feed
+ pub2 (/image_color) - color camera feed

+ publishRectified (/camera_rect/image_rect) - Redistributes the rectified image to the april tags detector

+ desiredTagPose (/tag_pose) - Publishes desired gun pose
"""

import math
import rospy
from cv_bridge import CvBridge
from sensor_msgs.msg import Image, CameraInfo, CompressedImage
import cv2
import actionlib
import tf
import numpy as np
from random import uniform
from darknet_ros_msgs.msg import BoundingBoxes
from apriltag_ros.msg import AprilTagDetectionArray
from geometry_msgs.msg import Pose, Point


# This class implements the image processing pipeline
# for our given task
class imageProcessor:


    # This node recieves from Baxter's camera
    # and publishes it in a format that YOLO ROS can use
    def process_initial_image(self, data):
        # pass
        # Publish the image we recieved so YOLO ROS can process it
        self.pub.publish(data)
        self.pub2.publish(data)

    def apriltag_callback(self, data):

        myPose = Pose()

        # print( data.detections[0].pose.pose.pose )
        
        if ( len(data.detections) > 0):
            #rospy.loginfo("Start publishing, pose is %lf,%lf,%lf",data.detections[0].pose.pose.pose.position.x,data.detections[0].pose.pose.pose.position.y,data.detections[0].pose.pose.pose.position.z)
            self.desiredTagPose.publish( data.detections[0].pose.pose.pose )
        else:
            pass

    # This method recieves the calibration matrix from Baxter's right arm
    # and publishes it to the correct topic so that apriltags can use it
    def publish_left_calibration(self, data):
        # Publish the info on the correct topic so apriltag_ros can use it
        self.calibrationMatrixLeftPub.publish(data)
        self.redistributeCameraInfo.publish(data)
        self.redistributeCameraInfo2.publish(data)


    def distributeRectified(self, data):
        self.publishRectified.publish(data)

    # Constructor method
    def __init__(self):
        self.leftCamera = rospy.Subscriber("/cameras/left_hand_camera/image", Image, self.process_initial_image)

        self.calibrationMatrixLeftSub = rospy.Subscriber("/cameras/left_hand_camera/camera_info_std", CameraInfo, self.publish_left_calibration)
        self.calibrationMatrixLeftPub =  rospy.Publisher("/camera/camera_info", CameraInfo, queue_size = 1)

        self.redistributeCameraInfo = rospy.Publisher("/camera_info", CameraInfo, queue_size = 1)
        self.redistributeCameraInfo2 = rospy.Publisher("/camera_rect/camera_info", CameraInfo, queue_size = 1)


        self.pub = rospy.Publisher("/image_raw", Image, queue_size = 1)
        self.pub2 = rospy.Publisher("/image_color", Image, queue_size = 1)

        # Redistributes the rectified image to the april tags detector
        self.rectifiedDistributor = rospy.Subscriber( "/image_rect", Image, self.distributeRectified )
        self.publishRectified = rospy.Publisher( "/camera_rect/image_rect", Image, queue_size = 1   )

        # /camera_rect/image_rect

        # Subscribe to the april tag classification data stream
        self.apriltags = rospy.Subscriber("/tag_detections", AprilTagDetectionArray, self.apriltag_callback)
        self.desiredTagPose = rospy.Publisher("/tag_pose", Pose, queue_size = 1 )

# Main Function
if __name__ == "__main__":

    rospy.init_node("key_locate")

    # create object
    my_imageProcessor = imageProcessor()

    # Keep the thread alive by spinning
    rospy.spin()
